//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lostandfound4.ReportLostFoundp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportLostFoundp.ReportLostFoundSoap")]
    public interface ReportLostFoundSoap {
        
        // CODEGEN: Generating message contract since element name losf from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report_lost", ReplyAction="*")]
        lostandfound4.ReportLostFoundp.report_lostResponse report_lost(lostandfound4.ReportLostFoundp.report_lostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/report_lost", ReplyAction="*")]
        System.Threading.Tasks.Task<lostandfound4.ReportLostFoundp.report_lostResponse> report_lostAsync(lostandfound4.ReportLostFoundp.report_lostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class report_lostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="report_lost", Namespace="http://tempuri.org/", Order=0)]
        public lostandfound4.ReportLostFoundp.report_lostRequestBody Body;
        
        public report_lostRequest() {
        }
        
        public report_lostRequest(lostandfound4.ReportLostFoundp.report_lostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class report_lostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string losf;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime datelosfou;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int locdes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string titl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string descr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string primcol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int cuid;
        
        public report_lostRequestBody() {
        }
        
        public report_lostRequestBody(string losf, System.DateTime datelosfou, int cat, int locdes, string titl, string descr, string primcol, string sno, int cuid) {
            this.losf = losf;
            this.datelosfou = datelosfou;
            this.cat = cat;
            this.locdes = locdes;
            this.titl = titl;
            this.descr = descr;
            this.primcol = primcol;
            this.sno = sno;
            this.cuid = cuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class report_lostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="report_lostResponse", Namespace="http://tempuri.org/", Order=0)]
        public lostandfound4.ReportLostFoundp.report_lostResponseBody Body;
        
        public report_lostResponse() {
        }
        
        public report_lostResponse(lostandfound4.ReportLostFoundp.report_lostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class report_lostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string report_lostResult;
        
        public report_lostResponseBody() {
        }
        
        public report_lostResponseBody(string report_lostResult) {
            this.report_lostResult = report_lostResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportLostFoundSoapChannel : lostandfound4.ReportLostFoundp.ReportLostFoundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportLostFoundSoapClient : System.ServiceModel.ClientBase<lostandfound4.ReportLostFoundp.ReportLostFoundSoap>, lostandfound4.ReportLostFoundp.ReportLostFoundSoap {
        
        public ReportLostFoundSoapClient() {
        }
        
        public ReportLostFoundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportLostFoundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportLostFoundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportLostFoundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lostandfound4.ReportLostFoundp.report_lostResponse lostandfound4.ReportLostFoundp.ReportLostFoundSoap.report_lost(lostandfound4.ReportLostFoundp.report_lostRequest request) {
            return base.Channel.report_lost(request);
        }
        
        public string report_lost(string losf, System.DateTime datelosfou, int cat, int locdes, string titl, string descr, string primcol, string sno, int cuid) {
            lostandfound4.ReportLostFoundp.report_lostRequest inValue = new lostandfound4.ReportLostFoundp.report_lostRequest();
            inValue.Body = new lostandfound4.ReportLostFoundp.report_lostRequestBody();
            inValue.Body.losf = losf;
            inValue.Body.datelosfou = datelosfou;
            inValue.Body.cat = cat;
            inValue.Body.locdes = locdes;
            inValue.Body.titl = titl;
            inValue.Body.descr = descr;
            inValue.Body.primcol = primcol;
            inValue.Body.sno = sno;
            inValue.Body.cuid = cuid;
            lostandfound4.ReportLostFoundp.report_lostResponse retVal = ((lostandfound4.ReportLostFoundp.ReportLostFoundSoap)(this)).report_lost(inValue);
            return retVal.Body.report_lostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lostandfound4.ReportLostFoundp.report_lostResponse> lostandfound4.ReportLostFoundp.ReportLostFoundSoap.report_lostAsync(lostandfound4.ReportLostFoundp.report_lostRequest request) {
            return base.Channel.report_lostAsync(request);
        }
        
        public System.Threading.Tasks.Task<lostandfound4.ReportLostFoundp.report_lostResponse> report_lostAsync(string losf, System.DateTime datelosfou, int cat, int locdes, string titl, string descr, string primcol, string sno, int cuid) {
            lostandfound4.ReportLostFoundp.report_lostRequest inValue = new lostandfound4.ReportLostFoundp.report_lostRequest();
            inValue.Body = new lostandfound4.ReportLostFoundp.report_lostRequestBody();
            inValue.Body.losf = losf;
            inValue.Body.datelosfou = datelosfou;
            inValue.Body.cat = cat;
            inValue.Body.locdes = locdes;
            inValue.Body.titl = titl;
            inValue.Body.descr = descr;
            inValue.Body.primcol = primcol;
            inValue.Body.sno = sno;
            inValue.Body.cuid = cuid;
            return ((lostandfound4.ReportLostFoundp.ReportLostFoundSoap)(this)).report_lostAsync(inValue);
        }
    }
}
